### ISSUE TITLE
Confirmation request could be more user friendly

### ISSUE THREAD

**Issue by sandordargo** [tipi-build/cli#25]
After running `tipi . -t linux-cxx17` for the first time, it asks whether the user is OK with downloading some 7GB:

```
By default tipi installs a subset of the build tools to build remotely on tipi.build. For local builds you can install them locally. This will download 7GB.
 Confirmation with : [y]es 
```
I hit enter and I leave for a coffee. I came back and nothing happened. I realized that I should have typed `y` or `yes`. After all, the request is clear. But it would be more user-friendly if we received an error message if we entered anything else, even if it's just an "enter".

---

While writing this issue, Grammarly reported that there are two missing commas in the above message.

According to Grammarly, the correct version is:
> By default, tipi installs a subset of the build tools to build remotely on tipi.build. For local builds, you can install them locally. This will download 7GB.

**Comment by pysco68** [comment]
Hi @sandordargo this one was really terrible wording in addition to being quite unfriendly in terms of UI. With v0.0.32 we have solved both, the message is better, friendlier and the prompt has a default answer too. Looking forward to your feedback!

Here's how it looks like:
![grafik](https://user-images.githubusercontent.com/90577/175087098-9dd884ea-ca6d-409f-87a7-711989f39a92.png)

Resolved in v0.0.32 / https://github.com/tipi-build/cli/releases/tag/v0.0.32
