### ISSUE TITLE
[Windows] Running the install script as non-admin after an earlier installation don't refresh tipi

### ISSUE THREAD

**Issue by daminetreg** [tipi-build/cli#31]
# Motivation
To install the new version of tipi some users might rely on the install script, it might not update the tipi version and simply do the download and run the old version without sending any errors.

## Steps to reproduce
1. Install tipi v0.0.29 as admin in powershell via the install script : 
```powershell
[Net.ServicePointManager]::SecurityProtocol = "Tls, Tls11, Tls12, Ssl3"
. { `
  iwr -useb https://raw.githubusercontent.com/tipi-build/cli/master/install/install_for_windows.ps1 `
} | iex
```
2. Install another version with `$env:TIPI_INSTALL_VERSION = "v0.0.30"` set for example in the **Non-admin** powershell window

**The installation finishes without error but it's still v0.0.29** 🙉 

## Expected behaviour
Error that the file cannot be replaced and installation failed.

**Comment by pysco68** [comment]
Resolved in v0.0.32 / https://github.com/tipi-build/cli/releases/tag/v0.0.32
