### ISSUE TITLE
[Windows] Systems that have PATH and Path case sensitive environment variable fails to start any action

### ISSUE THREAD

**Issue by daminetreg** [tipi-build/cli#33]
The windows process fails with "CreateProcess : executable file not found" or "CreateProcess: Access Denied" when there is a mismatch in case sensitivity of the Path and PATH variable in windows.

This is due to a bug in which tipi only appends path from it's distro tool to the "Path" variable and not the "PATH" one.

It's possible to work it around by going in the system environment and clicking : Edit Variable Text, then one can make sure the casing is the official windows one : "Path".

Some APIs don't make the difference between Path and PATH but the winapi one to set such var do.

**Comment by daminetreg** [comment]
Thanks @stefanofiorentino for helping us finding this one out !

**Comment by pysco68** [comment]
Resolved in v0.0.32 / https://github.com/tipi-build/cli/releases/tag/v0.0.32

Thank you again @stefanofiorentino  for the debugging session! We hope you'll like v0.0.32 🚀
