### ISSUE TITLE
Change tipi installation location with TIPI_HOME_DIR doesn't work

### ISSUE THREAD

**Issue by Bjoe** [tipi-build/cli#45]
Hi,

I try to change my tipi "Home"-Dir to `~/.local/share/tipi` via `TIPI_HOME_DIR`, but it doesn't work. The `tipi` command still expected the tipi home folder in `/usr/local/share/.tipi`

I saw in the [install_for_macos_linux.sh(https://github.com/tipi-build/cli/blob/master/install/install_for_macos_linux.sh#L97) script that it set `TIPI_DATA_DIR`. I try to set this also, but it's also not working.

Should I set this before I install tipi?

Btw. as workaround I created a "symlink" from `/usr/local/share/.tipi` to `~/.local/share/tipi`

May I ask a question, is there any reason why you use `/usr/local/share/.tipi` ? In linux/freedesktop they specified that user-specific data files should be stored to `$XDG_DATA_HOME` as default equal to `$HOME/.local/share`. See also https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html#variables

**Comment by daminetreg** [comment]
Hi @Bjoe,

Thanks for the info, we should have removed the information about the TIPI_HOME_DIR from the documentation, to allow and enable caching without restricting it to relocateable packages only ( which would otherwise require rewriting files path on extraction ) we don't support specifiying another installation location anymore.

The doc states it's no more possible in current version https://tipi.build/documentation/README#tipi-installation-location--former-tipi_home_dir-

Where did you find out about TIPI_HOME_DIR ?

It however is possible to use filesystem mountpoints to another disk location to support cases where you don't have enough space on your main hard disk.

**Comment by Bjoe** [comment]
Hi @daminetreg,

> 
> Thanks for the info, we should have removed the information about the TIPI_HOME_DIR from the documentation, to allow and enable caching without restricting it to relocateable packages only ( which would otherwise require rewriting files path on extraction ) we don't support specifiying another installation location anymore.
> 
> The doc states it's no more possible in current version https://tipi.build/documentation/README#tipi-installation-location--former-tipi_home_dir-
> 
> Where did you find out about TIPI_HOME_DIR ?
> 
Sorry, I mixed it up or didn't read proper and missed the word -> ***former*** TIPI_HOME_DIR <- ;-)
But I'm also confused about following in the Building in the tipi.build cloud doc:
```
...
Will provision an environment as described in ~/.tipi/<distro>/environments/linux.pkr.js
```
See https://tipi.build/documentation/00-environments#building-in-the-tipibuild-cloud

It should be on my "local" or on the "remote" machine?
>
> It however is possible to use filesystem mountpoints to another disk location to support cases where you don't have enough space on your main hard disk.
>
Hm, but when I already mount my "big hard drive" to `/home`, it's possible to symlink from `/usr/local/share/.tipi` -> `~/.local/share/tipi` ?

**Comment by daminetreg** [comment]
Hey @Bjoe,

Sorry for the delay replying here.

> It should be on my "local" or on the "remote" machine?
These are files that are local on your machine and that describes the tipi-build/environments that will get deployed remotely.


> Hm, but when I already mount my "big hard drive" to /home, it's possible to symlink from /usr/local/share/.tipi -> ~/.local/share/tipi ?

The symlink doesn't work, it has to be a real folder at that path, this is the way we guarante fixed path to enable using cache entries even in non-virtualized environments.

**Comment by Bjoe** [comment]
Ok thanks for the clarification
