### ISSUE TITLE
Broken contact link

### ISSUE THREAD

**Issue by matthew-dews** [tipi-build/cli#74]
When `tipi` hits an error it spits out this blurb:
```
[err] Something went wrong, for help on your issue, we would enjoy getting your report at https://tipi.build/#contact
```
The link appears to be broken, I don't think there is a contact anchor and from a ctrl+f I don't see contact info listed. The closest thing is the "Community Support" link in the very bottom left of the home page.

**Comment by daminetreg** [comment]
Thanks for reporting this @matthew-dews, it is now fixed. It's even a better contact section 👍
